name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        uses: cross-platform-actions/action@v0.23.0
        with:
          operating_system: freebsd
          version: '14.0'
          run: docker build . --file Dockerfile --tag usa_stock_finder:$(date +%s) --platform linux/arm/v7
